# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python library with poetry

env:
  COLUMNS: 120
  UV_CACHE_DIR: /tmp/.uv-cache
  
on:
  push:
    paths:
      - 'cliffy/**'
      - 'tests/**'
      - 'examples/**'
      - '!examples/generated/**'
  workflow_dispatch:
    

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        extras: [true] # false
        python-version: [ "3.13", "3.12", "3.11", "3.10", "3.9" ]
        os: [ubuntu-latest] # windows-latest, macos-latest
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load cached venv
      id: cache
      uses: actions/cache@v4
      with:
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}-${{ steps.setup-python.outputs.python-version }}-${{ matrix.extras }}
    - name: Install dependencies
      run: uv sync
      if: ${{ steps.cache.outputs.cache-hit != 'true' && matrix.extras == false }}
    - name: Install dependencies
      run: uv sync --all-extras
      if: ${{ steps.cache.outputs.cache-hit != 'true' && matrix.extras }}
    - name: Install library
      run: uv sync
      if: ${{ matrix.extras == false }}
    - name: Install library
      run: uv sync --all-extras
      if: ${{ matrix.extras }}
    - name: Code quality
      run: |
        source $VENV
        uv run make lint
    - name: Test with pytest
      run: |
        source $VENV
        uv run make test
    - name: Minimize uv cache
      run: uv cache prune --ci